/*
 * @Author: wkj（wkj.kjwoo.cn）
 * @Date: 2023-07-08 12:16:18
 * @LastEditTime: 2023-07-08 12:25:13
 * @Description: 字符常量
 */
export const strConst = {
    AMPERSAND: '&',
    AND: 'and',
    AT: '@',
    ASTERISK: '*',
    STAR: '*',
    BACK_SLASH: '\\',
    COLON: ':',
    COLON_CN: '：',
    COMMA: ',',
    COMMA_CN: '，',
    DASH: '-',
    DOLLAR: '$',
    DOT: '.',
    DOTDOT: '..',
    DOT_CLASS: '.class',
    DOT_JAVA: '.java',
    DOT_XML: '.xml',
    FILE: 'file',
    EMPTY: '',
    EQUALS: '=',
    FALSE: 'false',
    SLASH: '/',
    HASH: '#',
    HAT: '^',
    LEFT_BRACE: '{',
    LEFT_BRACKET: '(',
    LEFT_CHEV: '<',
    DOT_NEWLINE: ',\n',
    NEWLINE: '\n',
    N: 'n',
    NO: 'no',
    NULL: 'null',
    OFF: 'off',
    ON: 'on',
    PERCENT: '%',
    PIPE: '|',
    PLUS: '+',
    QUESTION_MARK: '?',
    EXCLAMATION_MARK: '!',
    QUOTE: '"',
    RETURN: '\r',
    TAB: '\t',
    RIGHT_BRACE: '}',
    RIGHT_BRACKET: ')',
    RIGHT_CHEV: '>',
    SEMICOLON: ',',
    SINGLE_QUOTE: "'",
    BACKTICK: '`',
    SPACE: ' ',
    // 全空格
    FULL_SPACE: '　',
    TILDA: '~',
    LEFT_SQ_BRACKET: '[',
    RIGHT_SQ_BRACKET: ']',
    TRUE: 'true',
    UNDERSCORE: '_',
    UTF_8: 'UTF-8',
    US_ASCII: 'US-ASCII',
    ISO_8859_1: 'ISO-8859-1',
    Y: 'y',
    YES: 'yes',
    ONE: '1',
    ZERO: '0',
    DOLLAR_LEFT_BRACE: '${',
    HASH_LEFT_BRACE: '#{',
    CRLF: '\r\n',
    HTML_NBSP: '&nbsp;',
    HTML_AMP: '&amp',
    HTML_QUOTE: '&quot;',
    HTML_LT: '&lt;',
    HTML_GT: '&gt;',
    GET: 'get',
    IS: 'is'
};
